eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: 
          username: 
          password: 
        native:
          search-locations: classpath:properties/
  application:
    name: config-service
  profiles:
    active: native  # 配置使用本地储存
 
#          URL与配置文件的映射关系如下：
#
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties
 
      
